import type { Metadata } from "next";
import "./globals.css";
import Navbar from "../components/shared/Navbar";
import { ThemeProvider } from "../components/shared/ThemeProvider";

export const metadata: Metadata = {
  title: "MyApp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="min-h-screen bg-background font-sans antialiased">
        <ThemeProvider>
          <Navbar />
          <main>{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
