import type { Metadata } from "next";
import "./globals.css";
import Navbar from "../components/shared/Navbar";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v16-appRouter";
import { ThemeProvider } from "@mui/material/styles";
import { theme } from "../components/shared/Theme";
import { CssBaseline, InitColorSchemeScript } from "@mui/material";

export const metadata: Metadata = {
  title: "MyApp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <InitColorSchemeScript attribute="data-mui-color-scheme"/>
        <AppRouterCacheProvider>
          <Navbar />
          <ThemeProvider theme={theme}>
            <CssBaseline />
            {children}
            {/* <Main open={false} /> */}
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
